Switch to github.com/golang-jwt/jwt
go-kit/kit pull request #1172
Opened 2021-07-27 15:49 UTC by vovinacci

Closes https://github.com/go-kit/kit/issues/1026

This PR switches to `github.com/golang-jwt/jwt` to address security vulnerability. More details in the issue and https://github.com/advisories/GHSA-w73w-5m7g-f7qc

2021-07-27 18:52 UTC, peterbourgon commented
@sagikazarmark Look good to you?

2021-07-28 01:22 UTC, sagikazarmark approved these changes

2021-07-28 01:32 UTC, sagikazarmark commented
After taking a more thorough look at the implementation, I'm not _sure_ that there is a breaking change, but I _suspect_ there might be.

Basically, those different types referenced in the public API are all interfaces and I assume the new package didn't break those overnight, so in _theory_ the replaced types could be backwards compatible with the old library.

In practice, though, some of the types used internally (eg. standard claims struct) are not interfaces, so those could break.

A simple test to check if there is a breaking change would be (temporarily) changing back the packages in tests to the old module to see if it works with the new code.

I'm not particularly worried about a breaking change (the library is basically abandoned after all), but if there is a breaking change, it should be released in a minor version, not a patch. Go 1.17 is just around the corner and Chris wants to cut a new release after that (hoping that we can further reduce the amount of dependency downloads).

2021-07-28 09:46 UTC, peterbourgon commented
OK let's bench this until the next release.

2021-07-28 11:21 UTC, vovinacci commented
@peterbourgon Do you have any preliminary release date in mind?

2021-08-14 19:11 UTC, AliLogic commented
Any updates on this?

2021-08-19 08:29 UTC, sagikazarmark requested changes
Can you please upgrade the library to v4?

2021-08-19 08:29 UTC, sagikazarmark commented on go.mod
> +	github.com/golang-jwt/jwt v3.2.1+incompatible
Looks like v4 is released with proper Go module support

2021-08-19 11:24 UTC, vovinacci commented
@sagikazarmark Done

2021-08-19 11:38 UTC, shogo82148 commented
I recommend to upgrade to Go 1.17 pruned module graphs.

https://golang.org/doc/go1.17#go-command

```
go mod tidy -go=1.17
```

It enables some optimizations, such as [Lazy module loading](https://golang.org/ref/mod#lazy-loading).

2021-08-19 17:12 UTC, eli-darkly commented
@shogo82148 If that would require setting the minimum version to 1.17 in go.mod, I would very strongly prefer that they _not_ make that change, at least not yet. Go 1.17 was just released and we can't all immediately update our projects to require it.

2021-08-19 21:00 UTC, sagikazarmark commented
> I recommend to upgrade to Go 1.17 pruned module graphs.

This is already in progress on another branch. Not sure which will be merged first yet.

2021-08-19 21:00 UTC, sagikazarmark approved these changes

2021-08-19 21:07 UTC, merged

2021-08-20 05:07 UTC, andig commented
> @shogo82148 If that would require setting the minimum version to 1.17 in go.mod, I would very strongly prefer that they _not_ make that change, at least not yet. Go 1.17 was just released and we can't all immediately update our projects to require it.

Imho this does not raise the minimum version.

2021-08-20 20:32 UTC, eli-darkly commented
@andig:
> Imho this does not raise the minimum version.

Could you say more about why you think it wouldn't? My reading of the linked documentation is that pruned module graphs are only a thing in `go.mod` files that specify `go 1.17`.

2021-08-20 22:09 UTC, shogo82148 commented
pruned module graphs are just `required` directives.
So, Go 1.16 or earlier parses them as extra dependencies.
This has no negative effects, because these extra dependencies are also in `go.sum` and Go 1.16 loads whole dependencies in `go.sum`.

The `go 1.17` directive enables new language features, and changes the `go` command behavior. https://golang.org/ref/mod#go-mod-file-go
However it doesn't break backward compatibility.

When Go 2.0 comes out in the future, Go 2.0 will not be able to import modules that contain the `go 1.17` directive.